hub_url=""
user_admin=""
user_noadmin=""
username_admin="beaker-auto-admin"
username_1_noadmin="beaker-auto-unadmin"
username_2_noadmin="beaker-auto-unadmin-2"
group_name="web-auto"
group_password="RedHat#1?"
